### ISSUE TITLE
Slice time axis after padding and convolution

### ISSUE THREAD

**Issue by vieting** [rwth-i6/returnn#1017]
I encountered an issue for a combination of padding, convolution and slicing. Specifically, the time axis is padded before convolution and sliced afterwards to ensure that it has the same length as before. This came up in https://github.com/rwth-i6/pytorch-to-returnn/issues/119 and here is a pure RETURNN test case to reproduce the issue.

```
def test_pad_conv():
  with make_scope() as session:
    net = TFNetwork(config=Config({"extern_data": {"data": {"dim": 5}}}))
    subnet_layer = net.construct_from_dict({
        "padding": {"class": "pad", "mode": "constant", "value": 0, "axes": ["T"], "padding": [(1, 1)], "from": "data"},
        "conv": {
          "class": "conv", "n_out": 5, "filter_size": (2,), "padding": "valid", "in_spatial_dims": ["T"],
          "from": "padding"},
        "output": {
          "class": "slice", "axis": "T", "slice_start": None, "slice_end": -1, "slice_step": None, "from": "conv"},
      })
```

**Comment by albertz** [comment]
PR #1018 should fix this.

However, you said this is supposed to make the length the same. While the length (in absolute number) is the same, it would not result in the same dim tag because the shift is different. It results in the dim tag `1 + input - 1`. To get the same dim tag out, the initial padding should be (0, 1) and there should be no slice at the end.

I'm not sure if you expect this. Or if you did not expect this, if this causes other problems.

**Comment by vieting** [comment]
Thanks a lot! It fixes the issue for me and right now I do not see that the different dim tag would cause any problems.
