### ISSUE TITLE
Failed Complie in Win Envrionment

### ISSUE THREAD

**Issue by NoahDragon** [rwth-i6/returnn#11]
``` python
EXCEPTION
Traceback (most recent call last):
  File "rnn.py", line 524, in <module>
    line: main(sys.argv)
    locals:
      main = <local> <function main at 0x0000007F9A9C0EA0>
      sys = <local> <module 'sys' (built-in)>
      sys.argv = <local> ['rnn.py', 'demos\\demo-tf-vanilla-lstm.12ax.config'], _[0]: {len = 6}
  File "rnn.py", line 511, in main
    line: init(commandLineOptions=argv[1:])
    locals:
      init = <global> <function init at 0x0000007F9A9C0BF8>
      commandLineOptions = <not found>
      argv = <local> ['rnn.py', 'demos\\demo-tf-vanilla-lstm.12ax.config'], _[0]: {len = 6}
  File "rnn.py", line 338, in init
    line: initFaulthandler()
    locals:
      initFaulthandler = <global> <function initFaulthandler at 0x0000007F9A641AE8>
  File "C:\Dev\returnn\Debug.py", line 194, in initFaulthandler
    line: if install_signal_handler_if_default(signal.SIGUSR1):
    locals:
      install_signal_handler_if_default = <global> <function install_signal_handler_if_default at 0x0000007F9A641950>
      signal = <global> <module 'signal' from 'C:\\AppData\\Local\\conda\\conda\\envs\\tensorflow\\lib\\signal.py'>
      signal.SIGUSR1 = <global> !AttributeError: module 'signal' has no attribute 'SIGUSR1'
AttributeError: module 'signal' has no attribute 'SIGUSR1'
```

As the Windows environment doesn't support the SIGUSR1 signal, this error occurs.

Any help will be appreciated.

**Comment by albertz** [comment]
I tried to fix it. Can you try again? Anyway, this faulthandler support is optional, so you can remove that. But patches to fix it are also welcome.

**Comment by NoahDragon** [comment]
@albertz Thank you very much for the fast reply. It solves the issue!

However, when runing the `demos/demo-tf-benchmark.py`, there is another issue raised, 

```bash
fatal error: tensorflow/core/framework/op.h: No such file or directory
```

Windows environment seems not suitable for the open source projects.

Thank you again for providing such awesome codes.

**Comment by albertz** [comment]
The TF benchmark uses also our native LSTM op, which it tries to compile on-the-fly.

It (the native LSTM op and other native ops) expects that it finds the TF header files. They are usually part of the PIP package of TF. It gets the path via `tf.sysconfig.get_include()`. Maybe you can check if that function returns a valid path for you and if you have the header files in there. Otherwise, it's a bit strange that the Windows PIP package does not contain the headers. Maybe you can report that upstream [here](https://github.com/tensorflow/tensorflow/issues).

The next thing is, it expects that there is a compiler. Currently there is `g++`/`nvcc` hardcoded and also the flags are probably partly specific for those. You will find related code in `TFUtil.OpCodeCompiler`. You would need to see how you can call the Windows default compiler and the relevant settings. See the TF documentation how to compile a custom op on Windows.

You don't need the native ops, though, if you don't use them. They are faster, esp the LSTM implementation is faster, but you can also use `LSTMBlockFused` for example. In that case it should work (or maybe you will hit another bug as Windows is not really tested by us). For example, you can try:

    rnn.py demos/demo-tf-contribrnn-lstm.12ax.config

Or:

    rnn.py demos/demo-tf-vanilla-lstm.12ax.config

You can also run the TF benchmark without the native op, e.g.:

    demos/demo-tf-benchmark.py --selected "BasicLSTM,StandardLSTM,LSTMBlock,LSTMBlockFused,CudnnLSTM"

**Comment by NoahDragon** [comment]
@albertz Great, everything works smooth now. I also created a PR to fix the print in config file to support python 3.5. 😄  https://github.com/rwth-i6/returnn/pull/12
Thanks for your patient help.
