### ISSUE TITLE
RangeInAxisLayer Docstring

### ISSUE THREAD

**Issue by vieting** [rwth-i6/returnn#1247]
The docstring of the `RangeInAxisLayer` says
> Assume that the input is e.g. (B,T,D), and you specify axis="T", you will get (B=1,T,D=1),

It seems to me that this is wrong, and you will actually get (T,). Would you agree, then I can fix this?

**Comment by albertz** [comment]
Yea, the option `keepdims` was intended to have this behavior. But it turned out that setting it to False was way more natural for RETURNN, and at some point I noticed that `keepdims=True` was actually broken, so then I changed the default and the option is not supported at all anymore.

So yes, please fix this.

**Comment by vieting** [comment]
Fixed with b6d584341b2d5306daa6d3b3da5949396b236a23
