### ISSUE TITLE
Potential infinite recursion between get_seq_length and get_seq_length_2d for base class Dataset

### ISSUE THREAD

**Issue by ArneNx** [rwth-i6/returnn#130]
I found a potential infinite recursion between the `get_seq_length` and the `get_seq_length_2d` method in the base class `Dataset`. 
```python
  def get_seq_length_2d(self, sorted_seq_idx):
    """
    :type sorted_seq_idx: int
    :rtype: numpy.array[int,int]
    :returns the len of the input features and the len of the target sequence.
    For multiple target seqs, it is expected that they all have the same len.
    We support different input/target len for seq2seq/ctc and other models.
    Note: This is deprecated, better use get_seq_length().
    """
    l = self.get_seq_length(sorted_seq_idx)
    targets = self.get_target_list()
    if targets:
      return numpy.array([l["data"], l[targets[0]]])
    else:
      return numpy.array([l["data"], 0])

  def get_seq_length(self, seq_idx):
    """
    :rtype: NumbersDict
    """
    input_len, output_len = self.get_seq_length_2d(seq_idx)
    d = {"data": input_len}
    d.update({k: output_len for k in self.get_target_list()})
    return NumbersDict(d)
```
As you can see, they would call each other in an infinite loop.

Fortunately, the sub-classes generally overwrite at least one of these methods. 
But we should still do something about this potential issue. Maybe we should make them abstract in the base class by default.

**Comment by albertz** [comment]
`get_seq_length` is the new (better, more generic) base function. Some older datasets only define `get_seq_length_2d`. Most of the new datasets just define `get_seq_length`. It's right that either one of them must be defined. (And yes, maybe this should be better documented. But did you actually really stumble upon this problem?)

Most other code uses `get_seq_length`. But also, there might be still some old code which calls `get_seq_length_2d`. So, to get rid of this function `get_seq_length_2d`, you should search for all its usages, and rewrite that code to call `get_seq_length` instead. Then you can remove `get_seq_length_2d` from the base class.

Do you want to do this? Or extend the doc? Otherwise I will close this for now.

**Comment by ArneNx** [comment]
I only noticed this when I tried to understand some related code and thought that this would be worth pointing out.
I will add the corresponding warning in the comments and leave it at that.
