### ISSUE TITLE
Possible race condition in `FileCache`?

### ISSUE THREAD

**Issue by NeoLegends** [rwth-i6/returnn#1542]
I had a training using `DistributeFilesDataset` fail due to missing disk space while copying a file onto the local disk with `FileCache`. I don't see how this can happen given that we check for enough free disk space before copying every file other than a race condition with another `FileCache` implementation or the disk suddenly shrinking in size. Given that we (by default) pre-fetch the files for the next epoch there are indeed two `FileCache` implementations at work at the same time which might get into conflict w/ each other.

I think we should _not_ put work into fixing the race condition itself, but rather be more tolerant to failure by allowing a couple retries (3-5) for cleanup + copying onto the local disk before actually giving up.

**Comment by albertz** [comment]
Well obviously there are many race conditions and we cannot really avoid them. There can also be other jobs maybe running on the same node which also write to `/var/tmp`. In fact, many things potentially could concurrently write stuff there which we have no control over.

> or maybe the old, unused files of the first epochs were never released properly and for that reason always kept around and never removed?

This would be some bug which we should check. There could also be other bugs.

But assuming all is working as intended:

I also wonder, despite `need_at_least_free_space_size`, there is `cleanup_disk_usage_wanted_free_ratio`. Maybe our default for `cleanup_files_wanted_older_than_days` is also bad so that we rarely get to this point and then only `need_at_least_free_space_size` is used?

Maybe instead of trying to free only `need_at_least_free_space_size`, it should free somewhat more than that? At least if possible. Actually `cleanup_files_wanted_older_than_days` is intended for that.

Multiple concurrent `FileCache`s from the same training run could be problematic. Maybe when starting to copy the file, we could immediately reserve the space?

**Comment by albertz** [comment]
> Multiple concurrent `FileCache`s from the same training run could be problematic. Maybe when starting to copy the file, we could immediately reserve the space?

Another idea: The lock file would not just be for the file itself but actually for the whole `cache_directory`. Then no concurrent copies can happen. At least from this user - if there are jobs from other users, you still have the problem...
