### ISSUE TITLE
Ideas for generic `CachedFile` support across all datasets

### ISSUE THREAD

**Issue by NeoLegends** [rwth-i6/returnn#1544]
WDYT about adding a global `FileCache` to RETURNN and passing every dataset kwargs through `FileCache.handle_cached_files_in_config` in `init_dataset`?

The support for this would also have to ensure we de-register the relevant files when a dataset is de-initialized. I'm not yet sure how to best do this generically. Maybe we can remember the cached files we have gotten from a dataset and then store them in the dataset somewhere for deregistration in `__del__`?

cc @albertz @michelwi @Icemole

**Comment by michelwi** [comment]
Yes, that would obsolete #1545. I would like that.

**Comment by albertz** [comment]
I'm not sure if calling `handle_cached_files_in_config` for every dataset causes maybe some weird behavior. E.g. when `DistributeFilesDataset` is used, you don't want the caching to happen at this point but the dataset should handle it. (Ok, in practice, you just pass the function `get_sub_epoch_dataset`, so maybe you don't have it in there. But maybe there are other similar examples.)

Note that a couple of datasets already derive `__del__`. So we need to make sure to call `super().__del__()` in those then.

Note that we don't necessarily want to have a global `FileCache`. Currently every instance holds a set of files it is responsible for to keep alive. Once the `FileCache` is deleted, it will stop keeping those files alive. So having a separate instance of `FileCache` per dataset actually seems to make more sense.

If we always create a `FileCache` instance, maybe `_TouchFilesThread` should only lazily be created on first actual usage.

We could also redesign this a bit, have one global `FileCache`, and use sth like our `_FileCacheExitHook`. Not sure...

**Comment by NeoLegends** [comment]
Good points! Let's discuss the implementation details in #1546

**Comment by NeoLegends** [comment]
Having one `FileCache` per dataset conceptually makes the most sense to me and runs the lowest risk of cleanup failure IMO. If there's one global instance I feel like the chance of running into issues w/ accidentally keeping files alive for longer than they should be is increased.

I feel like we don't even need a separate thread for the caching operations -- we need to block for caching anyway until we can load any data. So the asynchronity is only really relevant for datasets that use child processes for async loading, like `DistributeFilesDataset`, and they can deal with it on their own by running `init_dataset` in the child process.

**Comment by albertz** [comment]
> Good points! Let's discuss the implementation details in #1546

Actually I would prefer to first discuss here in general how we should do it, before we go over to discuss more fine-grained details of some code changes.


> Having one `FileCache` per dataset conceptually makes the most sense to me and runs the lowest risk of cleanup failure IMO. If there's one global instance I feel like the chance of running into issues w/ accidentally keeping files alive for longer than they should be is increased.

It depends what we keep local and what global. Sth like `_FileCacheExitHook` can be local.

Btw, I realized, we don't even need to overwrite the `Dataset.__del__`. `_FileCacheExitHook.__del__` is enough.


> I feel like we don't even need a separate thread for the caching operations

Which thread do you mean? `_TouchFilesThread`? But this thread does sth different. Or you mean not a thread but the sub proc `_FileCacheProc`? But this is important because it could influence the main proc otherwise. Even the logic from `_TouchFilesThread` which runs inside `_FileCacheProc`.


> -- we need to block for caching anyway until we can load any data.

`_TouchFilesThread` runs always in background, and I wanted to have this in a subproc.

For the file copying + cache cleanup, this depends on where this is called. If this is at RETURNN startup, then it's fine. If this is anyway in a sub proc (e.g. via `MultiProcDataset` or `DistributeFilesDataset`), it's also fine. Not sure about other cases.


> So the asynchronity is only really relevant for datasets that use child processes for async loading, like `DistributeFilesDataset`, and they can deal with it on their own by running `init_dataset` in the child process.

In `DistributeFilesDataset`, I wanted to have one instance of the `FileCache` shared for all sub datasets. But maybe that's not really necessary? Probably that's not necessary, so that can be simplified. Then we can really have the `FileCache` be handled in the sub proc for the sub dataset. That would simplify the code a bit.

**Comment by albertz** [comment]
Btw, there is another aspect we should keep in mind: When using PyTorch with `DataLoader` `num_workers=1` (as I would generally recommend), it means that there is one instance of the dataset first in the main proc, and then PyTorch will pickle it and create another copy of the dataset (by unpickling) in the `DataLoader` sub proc. This has caused a bit of trouble in some cases. Not sure if there are any issues here.

**Comment by NeoLegends** [comment]
Just for my understanding: when we block for `_FileCacheProc` on `channel.recv()`, where does this help relieve "influence" of the caching on the main proc? It still blocks after all. Maybe it releases the GIL, but what other code (except for touch files proc) would be able to run while this is blocked?

**Comment by albertz** [comment]
When this runs in a background thread during training, then e.g. the training runs at the same time.

But when we move this logic to the sub proc of the sub datasets in `DistributeFilesDataset`, it should not be an issue.

Originally I thought that it would be good to share the `FileCache`, but not sure. E.g. there is `_recent_full_cleanup_time`. I wanted that the full cleanup is not done too often. Now when every dataset or sub dataset has its own `FileCache`, this does not really work correctly anymore.

**Comment by NeoLegends** [comment]
> When this runs in a background thread during training, then e.g. the training runs at the same time.

Does the training loop run in a dedicated thread so when the GIL is released it can run?

**Comment by albertz** [comment]
> Does the training loop run in a dedicated thread so when the GIL is released it can run?

The other way around usually: The training loop runs in the main thread, but dataset related stuff was done in a background thread. At least for TF we did it this way. Although the `init_dataset` itself was not (yet) done in a background thread. For PT we also thought about doing it this way but then currently `DataLoader` with `num_workers=1` also solves this, so we do not. Also keep in mind that nothing here is really set in stone, and we might change it some point in the future.

So that's why I'm a bit hesitating to say that it would not influence anything. We don't really know what else is happening at the same time. A sub proc will just avoid any such issues.

**Comment by albertz** [comment]
> _recent_full_cleanup_time

Small idea: We maybe could have some specific file in the cache dir like `.recent_full_cleanup` which we touch, and then we can just compare the mtime of this file. That way, we can easily have multiple instances of `FileCache` working independently from each other.

Another thing: The `FileCache.cleanup` probably should also acquire the cache dir lock.

**Comment by NeoLegends** [comment]
So. The current implementation in #1546 works as following:

Caching always happens within `init_dataset`. This means:
- If we're using just a single dataset that on its own does not involve any sub procs or so, caching happens at startup when the dataset is loaded.
- When we use a dataset that uses sub processes, particularly in `DistributeFilesDataset`, the caching happens inside the subproc where the dataset is initialized.

Currently the implementation _does not_ use a separate sub process just for the cache. Given that caching will happen at startup or within a subprocess anyway, I think this is fine. I can introduce a subprocess if you want, but we'd still have to block in `init_dataset`, so the subprocess only really serves as a memory barrier, except for releasing the GIL the main thread will still not be able to do any work in the meantime.

What isn't solved yet is making caching for the "prefetched" subepochs in `DistributeFilesDataset` lower priority, but this belongs to a different issue anyways IMO.

**Comment by albertz** [comment]
> Cleanup happens when the `FileCache` instances owned by the datasets are deleted/GC'ed. I'm not sure if this can be made deterministic w/o introducing special cleanup logic into the datasets other than `__del__`. Does `del x` run `x.__del__()` deterministically? Probably a context manager would be the better approach here.

What do you mean by deterministic? The time when this executes, and also the thread in which this executes, is very much non-deterministic. It might not even execute at all when CPython is shutting down. But none of that should be an issue for us? It's totally ok when it maybe gets called a second later or so. It's also totally ok if it runs in another thread. And if it does not execute anymore at CPython shutdown time, it also doesn't matter.

**Comment by albertz** [comment]
> What isn't solved yet is making caching for the "prefetched" subepochs in `DistributeFilesDataset` lower priority, but this belongs to a different issue anyways IMO.

It's only really a problem for startup, and there also only when the files are not already cached. So it's probably not so important now.

**Comment by albertz** [comment]
> It is pretty important the unused files are deregistered after a couple minutes at worst during large trainings w `DistributeFilesDataset`. If they're kept alive even when they're no longer needed `/var/tmp` risks running full. I'm not talking about seconds or shutdown (that case doesn't matter for us), but we should make sure we dispose of the sub datasets for older epochs in reasonable time frames, such that we can free space on the local disk.

Yes sure, but the GC calling `__del__` in time should really not be the issue. If we have some issue here, it's probably some logic error on our side, that we still keep some reference to the dataset alive somewhere or so.

Btw, with `DistributeFilesDataset`, as sub datasets run in sub procs, and we create separate sub procs for every sub epoch, it also should not be an issue, because it should also stop the other sub procs anyway.

**Comment by albertz** [comment]
Ok, but then I think the changes in the PR #1546 are ok. Only missing now is the logic with the `.recent_full_cleanup` file.
