### ISSUE TITLE
Clarification of beam selection in "prev:"-layers

### ISSUE THREAD

**Issue by patrick-wilken** [rwth-i6/returnn#174]
Hi,

I noticed TFNetwork.get_search_choices() returns `prev:<layer_name>` also for cases where the last choice actually occurs two or more steps ago (`prev:prev:<layer_name>` so to say).

Am I right that this is exactly what is "fixed" by _SubnetworkRecCell.get_output().body().maybe_transform() ? Here we seem to translate what would become `prev:prev:<layer_name>` to `prev:<layer_name>`, such that get_search_choices() then corresponds to the right search choices when translating beams (because part of the translation is already done).

If so, this is super-non-obvious and definitively should be documented in both places! 

An example of this would be `energy_in` in `test_rec_layer_move_out_of_loop()`. I would have expected that the beams of `weight_feedback` have to be translated to the ones of `prev_s_transformed`, because the first ones stem from `prev:prev:output`, the latter ones from `prev:output`. But they aren't. This is nevertheless correct because `prev:accum_att_weights`, which are input to `weight_feedback`, are translated via maybe_transform(), right?

**Comment by albertz** [comment]
Yes, sth like `prev:prev:...` is not supported currently (neither for the normal data, nor for the choices) (and not sure if it is worth it to add such a support - it would complicate everything a lot, and in all cases, it is easy to work around needing that, e.g. just by `CopyLayer`).

I don't remember all the details now, but I think you are exactly right with your explanation. This is also already documented in `maybe_transform`. Where do you suggest to document this further? I'm very open for any extensions to the documentation.

Btw, many of these related test cases are all very high level, and don't check much, except that the creation of the network (either for training or searching) works without an exception, as well as maybe one train or search step. But nothing more. E.g. they don't really check whether the transformation of the search choices is correct in all the possible cases (the beam size is always the same, so likely there would not be any exception). I somewhat feel uncomfortable about this, because as you see, the code is highly non-trivial, and I assume it is easy to have something wrong there. But it is also very difficult to write test cases which really check for correctness. I currently don't have a good solution for this.

**Comment by albertz** [comment]
In `test_rec_layer_move_out_of_loop`:
* `energy_in` is via `weight_feedback` and `prev_s_transformed`.
* `prev_s_transformed` is via `prev_s_state`, i.e. via `prev:s`, i.e. via `prev:output`.
* `weight_feedback` is via `prev:accum_att_weights`, i.e. via `prev:energy_in`.
* `accum_att_weights` is via `att_weights`, i.e. via `energy_in`.

And `SearchChoices` referring to sth like `prev:prev:output` are not handled / do not exist - it will always refer to `prev:output` or `output`. So I think it should be correct as it is.

**Comment by patrick-wilken** [comment]
We don't need support of `prev:prev:` in the network definition, I agree. All I was saying is that even with `prev:` layer dependencies the search choices can be further back in the past. The way this is handled is actually clever, but I tried to make beam selection work in the case of multiple choice layers in the loop for weeks, without noticing how those `prev:prev:` cases are handled.
In `maybe_transform()` the comment says what is done, but not why ;) I will add to the comment once I'm submitting my changes.

BTW, I got Factored NMT working for quite some time now (despite this issue) and can match baseline performance, but as you said it is really hard to debug beam selection and be sure that everything works perfectly. And I needed much more changes than only the ChoiceLayer code I submitted. I hope to be able to finish this soon, i.e. make a clean and general version, but again, this is heavy stuff ':D

**Comment by albertz** [comment]
Are you planning to make a pull request for this (for extending the doc)? Note that I'm also currently working on all this code regarding search choices. In my latest commit, I also extended the doc of `maybe_transform` slightly. I'm also trying to get multiple search choices into one rec layer, and I'm fixing various issues for that currently, step by step.

If you don't plan to extend the doc more, I guess we can close this issue.

**Comment by patrick-wilken** [comment]
I won't have time for this in the following weeks, sorry. But I can give you my code and briefly explain the main ideas. Maybe this can help you.
