### ISSUE TITLE
How to save n-best hypothesis in beam search?

### ISSUE THREAD

**Issue by wd929** [rwth-i6/returnn#197]
hi, if I set beam_size=8 and want to save 8 hypothesis, how to get these hypothesis?

**Comment by albertz** [comment]
I guess you mean for the search task, right?
It always outputs from your output layer. If that has beams, it will output all beams. Otherwise only a single hypothesis.
I guess you have `search_output_layer = "decision"` or sth like that in your config, which is only the best hypothesis. Just use `search_output_layer = "output"` or so instead, which has all the beams.

**Comment by albertz** [comment]
Closing now. I guess there is no issue in RETURNN, and the question has been answered. Please just ask further questions here if you have any.
