### ISSUE TITLE
Any layer to generate one-hot of an input?

### ISSUE THREAD

**Issue by ragnarlbrok** [rwth-i6/returnn#259]
Is their any layer in returnn to apply tf.one_hot on input with shape (batch,time) and generate output  with shape (batch,time,depth). I tried to do it with eval but threw error on shape mismatch between output.placeholder & batch_ndim.

**Comment by albertz** [comment]
No, there is not. But it's probably simple to add.

The reason I did not add it yet is because in almost all cases, it would be inefficient to use. E.g. for `LinearLayer`, if you feed in a sparse input (batch,time) (this is what we call "sparse", i.e. the values represent indices; see doc of class `Data`), it will automatically do lookups in the corresponding weight matrix. Doing such lookups is **much more efficient** than first doing a one-hot, and then matrix multiply.

Where do you need it? I guess it makes more sense to extend the next layer, where you would use it, to support such sparse input directly, as this becomes much more efficient (as explained).

If you still want to have it, in `EvalLayer` it becomes a bit tricky as you need to specify `out_type` correctly. But maybe sth like `"out_type": {"sparse": False, "dtype": "float32"}` would work. Maybe we can just add such a layer instead.

**Comment by ragnarlbrok** [comment]
I need that for creating some mask in (batch,time) & layer will filter inputs coming from more than two layer, so each time step will take input from different layer based on mask. For now I implemented separate layer for one.hot analogous to LinearLayer using tf.one_hot. Do you have some better way to implement in returnn for choosing different layers input for different time step in a layer?

**Comment by albertz** [comment]
I did not quite understand why you need one-hot for that, or how that is even helpful. Maybe I understand wrong what you exactly want. Is `SwitchLayer` (wrapper around `tf.where`) not exactly what you want?

**Comment by ragnarlbrok** [comment]
I looked into SwitchLayer. Yes same  may be possible with SwitchLayer also . but for more than two values maybe multiple Switchlayers will be needed.

**Comment by albertz** [comment]
Yes. We could extend `SwitchLayer` for that. In any case, this should be more efficient than doing one-hot. Also, extending `SwitchLayer` would only have the effect that your config might look nicer, but performance wise there will be no different, as in any case, it would map to the same `tf.where` logic. So using multiple `SwitchLayer` is totally fine.

I'm closing this for now. If you still want a OneHotLayer, feel free to make a pull request. If you want to extend SwitchLayer, also feel free to make a pull request. But as said, both are not really needed.
