### ISSUE TITLE
Large (unneeded?) files created

### ISSUE THREAD

**Issue by ChristopherBrix** [rwth-i6/returnn#260]
I noticed that RETURNN creates some folders that contain logs. These can accumulate and take up quite some storage, is it save to delete them after the training/decoding is finished?
Specifically, I am talking about the following folders:

 - `train-2019-08-13-13-06-45`: One per training run. May be some GB large. Contains:
    - a large number of `events.out.tfevents.1565714698.cluster-cn-252` files 
    - one `returnn.2019-08-13-13-06-45.cluster-cn-252.8850.log` file
    - one `returnn.config` copy of the config
 - `dev-99-2019-11-22-08-25-43` (or `eval-...`): One per epoch. About 7 MB. Contains:
    - one `events.out.tfevents.1574510552.cluster-cn-274` log file
    - one `returnn.2019-11-22-08-25-43.cluster-cn-274.30501.log`  file
    - one `pooling_300.config` copy of the config
 - `dataset_id23280117335152-75-search-2019-10-28-15-06-28`: One per evaluated checkpoint (?). 2MB. Contains the same logs and config files as the `dev-` folder

I heard that the `tfevents` files from the training folder can be loaded into TensorBoard to visualize the training progress. Apart from that, is there any use to these files?
Individually they are reasonably small, but some users have more than 10k `dev-` folders, so it adds up.

**Comment by albertz** [comment]
Please check the TensorFlow documentation about the tfevents files. Their main purpose is for logging, and yes, TensorBoard is probably the main tool to visualize them. There is no other use in them. You can delete them if you don't need them. You can also set `tf_log_dir = None` explicitly in the config such that Returnn will not create them.

That said, they should not be so big. I just checked some of my models, and the total training logs are 50MB, dev takes 44MB, and the search logs takes 5.6MB. I.e. all logs combined take still much less than a single model file, so I don't think you should care too much about it, and always leave them there, as they are very helpful for debugging.
(Small edit: I checked some of my Transformer models now, and I see that they are much bigger, about 1GB in total. But still ok.)

So I wonder, you mentioned they are several GB for you. This sounds like you do sth strange (e.g. accidently dump all attention weights into them or so?), or some bug. You should inspect the tfevents files to see what really is in there (there some some TF tools to list e.g. the raw content). It might be due to the TF computation graph, which I think is also stored in these files, and even in every single file. We could also disable that specifically, although TensorBoard also wants it for visualization.

**Comment by albertz** [comment]
Maybe we can simply dump the computation graph only once at startup, and also only for training or so. It's basically the line `writer.add_graph(sess.graph)` in the code. We could also create a separate writer only for that. Contributions/suggestions are welcome.

**Comment by ChristopherBrix** [comment]
Sorry for the late reply. I am not running any experiments with RETURNN right now, but once I do so again, I will monitor the size of these files and try to understand why they become so large.
I will reopen this if I find any useful information or have further questions concerning the change you proposed.
