### ISSUE TITLE
Error in case of Distributed setup

### ISSUE THREAD

**Issue by manish-kumar-garg** [rwth-i6/returnn#265]
Hi, I am getting
`AssertionError: No parent dir of '/home/ubuntu/anaconda3/lib/libcudart.so.10.1.243' is a valid CUDA path.`
while using distributed setup.
Full stdout [here](https://gist.github.com/manish-kumar-garg/882926f279fdacb7e6848c250a247230)

**Comment by albertz** [comment]
This is due to Anaconda, as it does not come with a complete CUDA installation.
I would recommend to just not use Anaconda. It should be much simpler to use a standard Python installation.
Otherwise, try to delete the libcuda* files from Anaconda, and make sure that you have a real normal CUDA installation somewhere else.
