### ISSUE TITLE
RETURNN causes a freeze when run inside a docker container with log_verbosity 3 or 4

### ISSUE THREAD

**Issue by JackTemaki** [rwth-i6/returnn#293]
When not specifying the `-t` flag for TTY emulation when executing `docker run` with an RETURNN application inside, RETURNN will cause a freeze when log_verbosity is 3 or 4. This is due to the interactive progress bar. Somehow the `terminal_size` function does not recognize that a terminal window is not available, causing a freeze later on.

**Comment by albertz** [comment]
Are you sure? I don't expect that there is a problem with `terminal_size`. What do you think is the problem there? Can you show the exact stack trace of all running threads when it hangs? (E.g. by sending a SIGUSR1.)
I would rather expect that maybe there is no buffering, or too less, or no process is reading from the stdout so that is why it hangs.
In most possible cases I can think about here, this would not really be an issue with RETURNN, but rather some issue with your configuration, Docker, or so.

**Comment by JackTemaki** [comment]
It seems you are right, it was not possible for me to reproduce the error today. I am closing this.
