### ISSUE TITLE
Attention without encoder dependency

### ISSUE THREAD

**Issue by JackTemaki** [rwth-i6/returnn#303]
To implement Dynamic Convolution Attention without ugly workarounds, I would like to have the possibility to run this attention model:

```python
def test_attention_no_encoder_dependency():
  from GeneratingDataset import DummyDataset
  seq_len = 5
  n_data_dim = 2
  n_classes_dim = 7
  train_data = DummyDataset(input_dim=n_data_dim, output_dim=n_classes_dim, num_seqs=2, seq_len=seq_len)
  train_data.init_seq_order(epoch=1)
  dev_data = DummyDataset(input_dim=n_data_dim, output_dim=n_classes_dim, num_seqs=2, seq_len=seq_len)
  dev_data.init_seq_order(epoch=1)

  config = Config()
  config.update({
    "model": "%s/model" % _get_tmp_dir(),
    "batch_size": 5000,
    "max_seqs": 2,
    "num_outputs": n_classes_dim,
    "num_inputs": n_data_dim,
    "num_epochs": 1,
    "network": {
      "encoder": {"class": "linear", "activation": "tanh", "n_out": 5},
      "enc_transformed": {'class': 'linear', 'from': ['encoder'], 'n_out': 6, 'activation': None},
      "output": {
        "class": "rec",
        "from": [],
        "target": "classes", "max_seq_len": 10,
        "unit": {
          'output': {'class': 'choice', 'target': 'classes', 'beam_size': 4, 'from': ["output_prob"]},
          "end": {"class": "compare", "from": ["output"], "value": 0},
          'orth_embed': {'class': 'linear', 'activation': None, 'from': ['output'], "n_out": 7},
          "s": {"class": "rnn_cell", "unit": "LSTMBlock", "from": ["prev:c", "prev:orth_embed"], "n_out": 7},
          "output_prob": {"class": "softmax", "from": ["prev:s", "c"], "target": "classes", "loss": "ce"},

          # basic attention stuff
          "s_transformed": {'class': 'linear', 'from': ['s'], 'n_out': 6, 'activation': None},
          "att_energy_tanh": {'class': 'activation', 'from': ['att_energy_in'], 'activation': 'tanh'},
          "att_energy": {'class': 'linear', 'from': ['att_energy_tanh'], 'n_out': 1, 'activation': None},
          "att_weights": {'class': 'softmax_over_spatial', 'from': ['att_energy']},

          # feedback
          "accum_att_weights": {'class': 'combine', 'kind': 'add',
                                'from': ['prev:accum_att_weights', 'att_weights']},
          "convolved_att": {'class': 'conv', 'from': ['prev:accum_att_weights'], 'filter_size': (3,),
                            'n_out': 4, 'padding': 'same'},
          "location_feedback": {'class': 'linear', 'from': ['convolved_att'], 'n_out': 6, 'activation': None,},
          # This works 
          #"att_energy_in": {'class': 'combine', 'kind': 'add', 'from': ['s_transformed', 'base:enc_transformed', 'location_feedback']},
          # This does not work
          "att_energy_in": {'class': 'combine', 'kind': 'add', 'from': ['s_transformed', 'location_feedback']},

          "c": {"class": "generic_attention", "base": "base:encoder", "weights": "att_weights"},
        },
      },
      "decision": {"class": "decide", "from": ["output"], "loss": "edit_distance"}
    },
    "debug_print_layer_output_template": True,
  })
  _cleanup_old_models(config)
  engine = Engine(config=config)
  print("Train...")
  engine.init_train_from_config(config=config, train_data=train_data, dev_data=dev_data)
  engine.train()

  engine.finalize()
```

The error message changes slightly depending on the `from` order, either:

```
TFNetwork.NetworkConstructionDependencyLoopException: Error: There is a dependency loop on layer 's'.
Construction stack (most recent first):
  s_transformed
  att_energy_in
  att_energy_tanh
  att_energy
  att_weights
  c
  s
  output_prob

```

or 

```
TFNetwork.NetworkConstructionDependencyLoopException: Error: There is a dependency loop on layer 'accum_att_weights'.
Construction stack (most recent first):
  accum_att_weights
  convolved_att
  location_feedback
  att_energy_in
  att_energy_tanh
  att_energy
  att_weights
  c
  s
  output_prob
```

I think this is somehow related to the fact that during construction the shape can not be infered from the ```GenericAttentionLayer``` itself.

**Comment by albertz** [comment]
I'm quite sure the error message is much longer than that, and probably also contains multiple errors at the same time. The whole output is relevant here. (Maybe too long to post all here, but then use some Gist instead or so.)

I assume this comes from `_SubnetworkRecCell._construct_template`. The logic in there is unfortunately quite complicated and contains a lot of heuristics. The goal of this function is to derive all shape (`Data`), state, dependencies, and beam search dependencies of all sub layers in the `RecLayer`. This gets tricky because of the circular dependencies (via `prev:...`). And normally many layers output (via `get_out_data_from_opts`) depends a lot on the input to the layer. So in general it would be impossible to really do this if there are circular dependencies. However, some `get_out_data_from_opts` work if some of the inputs are incomplete or unknown. It will try in a kind of brute-force way with a couple of heuristics. If it succeeds at some point, and everything looks consistent, it passes. If it fails, it will print all the collected exceptions along the way (so you get a long list of multiple errors). `NetworkConstructionDependencyLoopException` is kind of the standard and expected case there, which we might even omit in the future to not clutter the output too much.
(Go ahead and think about how you would solve this problem. It's not simple. Maybe you have some better ideas. Also check the current code, and try to understand it.)

When you study the whole stack trace (or the multiple collected stack traces and exceptions), you might find some layers behaving not well enough. I.e. they actually could return (via `get_out_data_from_opts`) some reasonable `Data` but they don't, or they are buggy. This is most often the case, and then you can just fix that layer, and it probably works.

You will also see the current partial constructed subnetwork templates which might additional help you to understand where exactly it goes wrong, or why it cannot resolve all the templates.

In really all cases I have seen so far, the solution was to fix or improve some `get_out_data_from_opts` of some layer. The annoying part was to find the problem itself and check through this huge error.

But maybe you also got a case which is really not possible in general to be solved this way.
Another way to help `_SubnetworkRecCell._construct_template` is to provide explicit `out_type` on some layers. `get_out_data_from_opts` should then pick up this existing `out_type` (but most `get_out_data_from_opts` implementations will actually ignore it currently... this is also somewhat incomplete... I think `EvalLayer`, `LinearLayer`, and some other basic ones should do that correctly, though; maybe `_construct_template` could also catch this more directly).

---

Some more specific comments (but they might be irrelevant, not sure):

`accum_att_weights` with `'from': ['prev:accum_att_weights', 'att_weights']` might have problems for the automatic shape deduction because it depends on itself and it iself is unknown. When you switch around the sources order (i.e. `'from': ['att_weights', 'prev:accum_att_weights']`), this might resolve it. I think the default `get_out_data_from_opts` will just fallback to the first source then.

I'm quite sure that `convolved_att` can easily behave incorrectly when moved out of the loop, because the `ConvLayer` currently expects that the convolution is over all spatial axes (i.e. this is 1D conv inside the `RecLayer`, but it is 2D conv outside). This can be fixed, though. Maybe it's anyway not a problem here.

**Comment by JackTemaki** [comment]
Ok, so before continuing on the Issue I will try to understand the code. My assumption is, that there is something in the `GenericAttention`layer that prohibits the correct shape construction from the "base" component.

I put the  other exceptions that occur here:
https://gist.github.com/JackTemaki/023407b1a973a03ee571e97ec2dd2ba5

**Comment by albertz** [comment]
From that log, all exceptions which are not `CannotHandleUndefinedSourcesException` or `NetworkConstructionDependencyLoopException` are buggy. Solving these might already solve the problem (but maybe also not).

* `ConvLayer` with `AttributeError: 'Data' object has no attribute 'setdefault'`.
* `GenericAttentionLayer` with `AttributeError: 'NoneType' object has no attribute 'output'`.
* `GenericAttentionLayer` with `ValueError: list.remove(x): x not in list`.
* `RnnCellLayer` with `AttributeError: 'NoneType' object has no attribute 'output'`.

All of these should be fixed.

**Comment by JackTemaki** [comment]
This will be dealth with in #313 and a further PR for the network construction Issues.
