### ISSUE TITLE
Difference in GPU-RAM consumptionen when switching axes

### ISSUE THREAD

**Issue by JackTemaki** [rwth-i6/returnn#367]
I have a baseline TTS config that looks as follows:
https://gist.github.com/JackTemaki/a3ac85be59c2274b64a0b8b88230c075

The part I changed is only this:
```python
            #'accum_att_weights': { 'class': 'eval',
            #                       'eval': 'source(0) + source(1)',
            #                       'from': ['prev:accum_att_weights', 'att_weights'],
            #                       'is_output_layer': True,
            #                       'out_type': {'dim': 1, 'shape': (None, 1)}},
            'accum_att_weights': {'class': 'combine',
                                  'kind': 'add',
                                  'from': ['prev:accum_att_weights', 'att_weights'],
                                  'is_output_layer': True},
```
So from an eval layer with a fixed out type to a combine layer with arbitrary out type. (It does not matter here if it is a combine or an eval layer, this is only about the output explicit output shape)

This led to the following changes in my shapes (this is only the attention feedback):

```patch
--- /u/rossenbach/asr4/LJSpeech_interspeech_tutorial/newatt_layers
+++ /u/rossenbach/asr4/LJSpeech_interspeech_tutorial/oldatt_layers
@@ -1,15 +1,15 @@
 layer root/'data:padded_data_target' output: Data(name='padded_data_target_output', shape=(None, 80), batch_shape_meta=[B,T|"time:var:'padded_data_target/mul:0':padded_data_target/padded_data_target_output",F|80])
-layer root/decoder:rec-subnet/'accum_att_weights' output: Data(name='accum_att_weights_output', shape=(1, None), time_dim_axis=2, feature_dim_axis=1, available_for_inference=False, batch_shape_meta=[B,F|1,T|'time:var:extern_data:classes'])
+layer root/decoder:rec-subnet/'accum_att_weights' output: Data(name='accum_att_weights_output', shape=(None, 1), time_dim_axis=None, available_for_inference=False, batch_shape_meta=[B,'time:var:extern_data:classes',F|1])
 layer root/decoder:rec-subnet/'att0' output: Data(name='att0_output', shape=(512,), time_dim_axis=None, batch_shape_meta=[B,F|512])
 layer root/decoder:rec-subnet/'att_energy_in' output: Data(name='att_energy_in_output', shape=(None, 128), batch_dim_axis=1, available_for_inference=False, batch_shape_meta=[T|'time:var:extern_data:classes',B,F|128])
 layer root/decoder:rec-subnet/'att_energy' output: Data(name='att_energy_output', shape=(None, 1), batch_dim_axis=1, available_for_inference=False, batch_shape_meta=[T|'time:var:extern_data:classes',B,F|1])
 layer root/decoder:rec-subnet/'att_energy_tanh' output: Data(name='att_energy_tanh_output', shape=(None, 128), batch_dim_axis=1, available_for_inference=False, batch_shape_meta=[T|'time:var:extern_data:classes',B,F|128])
 layer root/decoder:rec-subnet/'att_weights' output: Data(name='att_weights_output', shape=(1, None), time_dim_axis=2, feature_dim_axis=1, available_for_inference=False, batch_shape_meta=[B,F|1,T|'time:var:extern_data:classes'])
-layer root/decoder:rec-subnet/'convolved_att' output: Data(name='convolved_att_output', shape=(32, None), time_dim_axis=2, feature_dim_axis=1, available_for_inference=False, batch_shape_meta=[B,F|32,T|?])
+layer root/decoder:rec-subnet/'convolved_att' output: Data(name='convolved_att_output', shape=(None, 32), available_for_inference=False, batch_shape_meta=[B,T|?,F|32])
 layer root/decoder:rec-subnet/'decoder_1' output: Data(name='decoder_1_output', shape=(640,), time_dim_axis=None, batch_shape_meta=[B,F|640])
 layer root/decoder:rec-subnet/'decoder_2' output: Data(name='decoder_2_output', shape=(640,), time_dim_axis=None, batch_shape_meta=[B,F|640])
-layer root/decoder:rec-subnet/'feedback_pad_left' output: Data(name='feedback_pad_left_output', shape=(1, None), time_dim_axis=2, feature_dim_axis=1, available_for_inference=False, batch_shape_meta=[B,F|1,T|?])
-layer root/decoder:rec-subnet/'feedback_pad_right' output: Data(name='feedback_pad_right_output', shape=(1, None), time_dim_axis=2, feature_dim_axis=1, available_for_inference=False, batch_shape_meta=[B,F|1,T|?])
+layer root/decoder:rec-subnet/'feedback_pad_left' output: Data(name='feedback_pad_left_output', shape=(None, 1), time_dim_axis=None, available_for_inference=False, batch_shape_meta=[B,?,F|1])
+layer root/decoder:rec-subnet/'feedback_pad_right' output: Data(name='feedback_pad_right_output', shape=(None, 1), time_dim_axis=None, available_for_inference=False, batch_shape_meta=[B,?,F|1])
 layer root/decoder:rec-subnet-input/'choice' output: Data(name='choice_output', shape=(None, 160), batch_shape_meta=[B,T|"time:var:'windowed_data/Neg_1:0':windowed_data/windowed_batch/move_axis_2/windowed_data_output",F|160])
 layer root/decoder:rec-subnet-input/'data:windowed_data_target' output: Data(name='windowed_data_target_output', shape=(None, 160), batch_shape_meta=[B,T|"time:var:'windowed_data/Neg_1:0':windowed_data/windowed_batch/move_axis_2/windowed_data_output",F|160])
 layer root/decoder:rec-subnet-input/'pre_net_layer_1' output: Data(name='pre_net_layer_1_output', shape=(None, 128), batch_dim_axis=1, batch_shape_meta=[T|"time:var:'windowed_data/Neg_1:0':windowed_data/windowed_batch/move_axis_2/windowed_data_output",B,F|128])
@@ -17,8 +17,8 @@
 layer root/decoder:rec-subnet-input/'pre_net_layer_2' output: Data(name='pre_net_layer_2_output', shape=(None, 64), batch_dim_axis=1, batch_shape_meta=[T|"time:var:'windowed_data/Neg_1:0':windowed_data/windowed_batch/move_axis_2/windowed_data_output",B,F|64])
 layer root/decoder:rec-subnet-input/'pre_slice' output: Data(name='pre_slice_output', shape=(None, 80), batch_dim_axis=1, batch_shape_meta=[T|?,B,F|80])
 layer root/decoder:rec-subnet-input/'prev:choice' output: Data(name='windowed_data_target_output', shape=(None, 160), batch_dim_axis=1, batch_shape_meta=[T|"time:var:'windowed_data/Neg_1:0':windowed_data/windowed_batch/move_axis_2/windowed_data_output",B,F|160])
-layer root/decoder:rec-subnet/'location_feedback_transformed' output: Data(name='location_feedback_transformed_output', shape=(128, None), time_dim_axis=2, feature_dim_axis=1, available_for_inference=False, batch_shape_meta=[B,F|128,T|?])
-layer root/decoder:rec-subnet-output/'accum_att_weights' output: Data(name='accum_att_weights_output', shape=(None, 1, None), batch_dim_axis=1, feature_dim_axis=2, available_for_inference=False, batch_shape_meta=[T|"time:var:'windowed_data/Neg_1:0':windowed_data/windowed_batch/move_axis_2/windowed_data_output",B,F|1,'time:var:extern_data:classes'])
+layer root/decoder:rec-subnet/'location_feedback_transformed' output: Data(name='location_feedback_transformed_output', shape=(None, 128), available_for_inference=False, batch_shape_meta=[B,T|?,F|128])
+layer root/decoder:rec-subnet-output/'accum_att_weights' output: Data(name='accum_att_weights_output', shape=(None, None, 1), batch_dim_axis=1, available_for_inference=False, batch_shape_meta=[T|"time:var:'windowed_data/Neg_1:0':windowed_data/windowed_batch/move_axis_2/windowed_data_output",B,'time:var:extern_data:classes',F|1])
 layer root/decoder:rec-subnet-output/'att0' output: Data(name='att0_output', shape=(None, 512), batch_dim_axis=1, batch_shape_meta=[T|"time:var:'windowed_data/Neg_1:0':windowed_data/windowed_batch/move_axis_2/windowed_data_output",B,F|512])
 layer root/decoder:rec-subnet-output/'att_weights' output: Data(name='att_weights_output', shape=(None, 1, None), batch_dim_axis=1, feature_dim_axis=2, available_for_inference=False, batch_shape_meta=[T|"time:var:'windowed_data/Neg_1:0':windowed_data/windowed_batch/move_axis_2/windowed_data_output",B,F|1,'time:var:extern_data:classes'])
 layer root/decoder:rec-subnet-output/'data:stop_token_target' output: Data(name='stop_token_target_output', shape=(None, 1), batch_shape_meta=[B,T|"time:var:'windowed_data/Neg_1:0':windowed_data/windowed_batch/move_axis_2/windowed_data_output",F|1])
```

The maximum memory usage for the combine (`shape == (1, None)`) is 7.7Gb
The maximum memory usage for the eval layer (`shape == (None, 1)`) is only 5.0Gb

The computing time did not change significantly, and there is no difference in CUDA version, Tensorflow version or anything else.

So I do not think that a simple axes change of only a few layers would result in a memory consumption difference that large.

**Comment by albertz** [comment]
As you say, note that the change is not really from `EvalLayer` (which is `CombineLayer` with `kind="eval"`) to `CombineLayer` with `kind="add"`. The change is simply that you have specified `'out_type': {'dim': 1, 'shape': (None, 1)}` explicitly in the one case, and not in the other case. You could also specify that for the `CombineLayer`, or remove that for the `EvalLayer`. If you remove that, it should be exactly the same.

I always recommend to not explicitly specify `out_type`. You find it in some config examples, because it sometimes is necessary. Often for the template construction in the rec layer. Or was necessary, and maybe not even more, because the rec layer template construction got better now.

On the intended behavior:

* If you explicitly specify `out_type`, I think it is correct that RETURNN follows that, and uses your specification, even if it is suboptimal for memory consumption.
* If you do not specify `out_type`, the idea always is that it automatically selects the most optimal shape/format (not just `CombineLayer`, but for all layers). Basically you should not need to think about this.
  * If you find a case where it does not automatically use the optimal shape/format, but some suboptimal, consider this as a bug, and please report.
    (Although, there are also cases where it might be very difficult/hard to automatically infer/know what the optimal shape/format would be, so this is not always possible.)
  * If you find a case where it fails to automatically use the shape, although it should be able to, then also consider this as a bug, and please report.

So, as I understand it, in the automatic case here, it selects a suboptimal shape, so we might want to fix this (if this is possible in an easy way).
The suboptimal shape here is `[B,F|1,T|'time:var:extern_data:classes']`.
The better shape here is `[B,'time:var:extern_data:classes',F|1]`.

But first we should understand better where exactly the more memory consumption happens. This probably does not happen in the `accum_att_weights` layer itself, but in some on the others where this affects also a shape/format change. When you enable profiling, you should get the statistics, and see them in TensorBoard.

Also, what about runtime? Sometimes memory consumption goes up, but runtime goes down. Then this is not so clear, what we actual prefer. I often prefer better runtime, when the higher memory consumption is acceptable. It's a tradeoff. But maybe that's not the case here, and runtime is the same, or also goes up.

Also, to understand why it selects the suboptimal shape: It will use the shape from the first source, and then extend that to the further sources such that they can be combined (via broadcasting). In this case, the first source is the layer itself, so only `att_weights` matters.
`att_weights` has shape `[B,F|1,T|'time:var:extern_data:classes']`. So there is where it comes from. But actually this is a good shape for `att_weights`, and also optimal for the `GenericAttention`. So this should probably not be changed.
Maybe then actually the behavior of `CombineLayer`/`EvalLayer` is also fine, and we might just want to change some other layer here.
I assume that your `convolved_att` actually should perform better/faster/less-mem with [B|F|T], right?
So remaining is the question about `feedback_pad_*` and `location_feedback_transformed`. I don't really know... `location_feedback_transformed` is also the correct behavior in cases when you always have [B,F,T] (e.g. ResNet) -- it would be suboptimal (I think, maybe I'm wrong) to switch there to [B,T,F] and then back to [B,F,T].
What exactly are your `feedback_pad_*` layers?

**Comment by albertz** [comment]
@Spotlight0xff might also have some experience with cases like this.

**Comment by albertz** [comment]
Btw, I think we should not just try around here, and then if total mem consumption goes down, get to the conclusion that this is because of EvalLayer or whatever. This always will have indirect effects on other layers as well, because it propagates the shape. So whatever we test, we always should profile the mem per layer, and really understand what is happening. And then not fix the wrong thing which maybe causes the higher mem indirectly for this example.

Also, it would be really good if we have a small reproducible example. When you remove the encoder, and other stuff, and just use some generating toy dataset (e.g. `Task12AXDataset`, or whatever), we should also see this. And then you can try to reduce it further.

**Comment by JackTemaki** [comment]
> As you say, note that the change is not really from `EvalLayer` (which is `CombineLayer` with `kind="eval"`) to `CombineLayer` with `kind="add"`. The change is simply that you have specified `'out_type': {'dim': 1, 'shape': (None, 1)}` explicitly in the one case, and not in the other case. You could also specify that for the `CombineLayer`, or remove that for the `EvalLayer`. If you remove that, it should be exactly the same.

Yes, I wrote that in my Issue.

> I always recommend to not explicitly specify `out_type`. You find it in some config examples, because it sometimes is necessary. Often for the template construction in the rec layer. Or was necessary, and maybe not even more, because the rec layer template construction got better now.

This is why I fixed it now and found this behavior. The `eval`  layer was part of older ASR setups and survived until now.
> 
> On the intended behavior:
> 
>     * If you explicitly specify `out_type`, I think it is correct that RETURNN follows that, and uses your specification, even if it is suboptimal for memory consumption.
> 
>     * If you do not specify `out_type`, the idea always is that it automatically selects the most optimal shape/format (not just `CombineLayer`, but for all layers). Basically you should not need to think about this.
>       
>       * If you find a case where it does not automatically use the optimal shape/format, but some suboptimal, consider this as a bug, and please report.

This is exactly what I did here.

>         (Although, there are also cases where it might be very difficult/hard to automatically infer/know what the optimal shape/format would be, so this is not always possible.)
>       * If you find a case where it fails to automatically use the shape, although it should be able to, then also consider this as a bug, and please report.
> 
> 
> So, as I understand it, in the automatic case here, it selects a suboptimal shape, so we might want to fix this (if this is possible in an easy way).
> The suboptimal shape here is `[B,F|1,T|'time:var:extern_data:classes']`.
> The better shape here is `[B,'time:var:extern_data:classes',F|1]`.
> 
> But first we should understand better where exactly the more memory consumption happens. This probably does not happen in the `accum_att_weights` layer itself, but in some on the others where this affects also a shape/format change. When you enable profiling, you should get the statistics, and see them in TensorBoard.
> 
> Also, what about runtime? Sometimes memory consumption goes up, but runtime goes down. Then this is not so clear, what we actual prefer. I often prefer better runtime, when the higher memory consumption is acceptable. It's a tradeoff. But maybe that's not the case here, and runtime is the same, or also goes up.

I already wrote that the runtime is constant.

> 
> Also, to understand why it selects the suboptimal shape: It will use the shape from the first source, and then extend that to the further sources such that they can be combined (via broadcasting). In this case, the first source is the layer itself, so only `att_weights` matters.
> `att_weights` has shape `[B,F|1,T|'time:var:extern_data:classes']`. So there is where it comes from. But actually this is a good shape for `att_weights`, and also optimal for the `GenericAttention`. So this should probably not be changed.
> Maybe then actually the behavior of `CombineLayer`/`EvalLayer` is also fine, and we might just want to change some other layer here.
> I assume that your `convolved_att` actually should perform better/faster/less-mem with [B|F|T], right?
> So remaining is the question about `feedback_pad_*` and `location_feedback_transformed`. I don't really know... `location_feedback_transformed` is also the correct behavior in cases when you always have [B,F,T] (e.g. ResNet) -- it would be suboptimal (I think, maybe I'm wrong) to switch there to [B,T,F] and then back to [B,F,T].
> What exactly are your `feedback_pad_*` layers?

This is the relevant question. So none of the layers should cause this large change. There are two padding layers, one convolutional layer and one linear layer. So maybe the padding layer causes some large changes, I will check that.

**Comment by albertz** [comment]
> This is the relevant question. So none of the layers should cause this large change. There are two padding layers, one convolutional layer and one linear layer. So maybe the padding layer causes some large changes, I will check that.

But also check the difference by profiling, not just the final mem-consumption result. This might always be some indirect effect, and then we might fix the wrong thing if we draw wrong conclusions.

**Comment by JackTemaki** [comment]
The profiler graph unfortunately shows the same memory consumption for both graphs.

**Comment by albertz** [comment]
> The profiler graph unfortunately shows the same memory consumption for both graphs.

How did you profile it? Via `store_metadata_mod_step` as described [here](https://returnn.readthedocs.io/en/latest/advanced/profiling.html)?

I did not look too much as what else TF supports, but I think there are more tools. E.g. check [this](https://github.com/tensorflow/tensorflow/blob/b2edbd5a640fb2f50989c5579a4cfe87d1fc675e/tensorflow/core/profiler/README.md). Maybe this works better? Maybe there are other TF tools?

I think it should be possible to get some better information and see the behavior in a memory profiler.

Btw, is your behavior even deterministic? Maybe sometimes it produces less memory, and sometimes more.

**Comment by JackTemaki** [comment]
> > The profiler graph unfortunately shows the same memory consumption for both graphs.
> 
> How did you profile it? Via `store_metadata_mod_step` as described [here](https://returnn.readthedocs.io/en/latest/advanced/profiling.html)?

Yes.

> 
> I did not look too much as what else TF supports, but I think there are more tools. E.g. check [this](https://github.com/tensorflow/tensorflow/blob/b2edbd5a640fb2f50989c5579a4cfe87d1fc675e/tensorflow/core/profiler/README.md). Maybe this works better? Maybe there are other TF tools?
> 
> I think it should be possible to get some better information and see the behavior in a memory profiler.
> 
> Btw, is your behavior even deterministic? Maybe sometimes it produces less memory, and sometimes more.

No it not. I just increased the batch size for both models until it crashes, and it was exactly the same. So just the number is not accurate, there is no bug.

**Comment by albertz** [comment]
> > Btw, is your behavior even deterministic? Maybe sometimes it produces less memory, and sometimes more.
> No is not apparently. I just increased the batch size for both models until it crashes, and it was exactly the same. So just the number is not accurate, there is no bug.

Ok. :P

> EDIT: nevertheless, for some reason my TTS models now can sustain twice the batch size after switching from TF 1.13 to TF 2.3

Hm, ok, but this is not related to this `out_type` difference, but about the switch from TF 1.13 to TF 2.3?
Then, this is a good thing, I would say. I anyway recommend everyone now to switch to latest TF. We only would have a problem if memory consumption or runtime got worse.
