### ISSUE TITLE
DotLayer: Support shuffled remaining dimensions

### ISSUE THREAD

**Issue by Zettelkasten** [rwth-i6/returnn#406]
I have a config with a dot layer that takes two inputs of e.g. the shapes `[B,T,X,Y]` and `[T,B,Y,Z]`.
Then I want to compute their dot product, getting a tensor of the form `[B,T,X,Z]` (reduce the `Y` axis, have `X` and `Z` be the variable axes).

Note however that the the remaining axes (i.e. `B` and `T`) are equal but not in the same order for these two tensors.
Currently, this is not handled by `DotLayer` at all, it always assumes that all remaining axes are in the exact same order.
If they have static dimensions, than this will throw an error at template construction.
If not, the flag `debug=True` will assert that the shapes are compatible when the session is executed.
If that flag is not set, I guess TF would throw an error as well (except when it works because of broadcasting or sth like that).

Here is a small artificial example demonstrating this (with static shapes):
```
net_dict = {
  "a": {"class": "split_dims", "axis": "static:0", "dims": (2, 3, 5)},   # [B, 2, 3, 5]
  "b": {"class": "transpose", "from": ["a"], "perm": {"static:0": "static:1", "static:1": "static:0"}},  # [B, 3, 2, 5]
  "dot": {  # should produce [B, 2, 3, 1] or [B, 3, 2, 1], but throws an Exception instead
    "class": "dot", "from": ["a", "b"],
    "red1": "static:-1", "red2": "static:-1", "var1": None, "var2": None,
    "debug": True}
  # ...
}
```

To fix this, I think we need to transpose the remaining axes of one of the inputs to match each others order, which we can e.g.
determine by matching the `DimensionTag`s of the remaining axes using `DimensionTag.is_equal(..)` - similar to `get_common_data` does this as well.
But an extra `transpose` sounds inefficient (and from what I can tell from the code efficiency was considered thoroughly in the `DotLayer`) - perhaps we can integrate this better with the logic there already is in the layer?

Also: Why doesn't `DotLayer` use `tf.einsum` instead of `tf.matmul`? This would handle those index permutations by itself. (I guess performance? Or maybe backwards compatibility?)

**Comment by albertz** [comment]
That should work, obviously. It also did work in the past (your first example [B,T,X,Y] and [T,B,Y,Z]; I assume T is dynamic), because we always used `copy_as_batch_major`. However, that was removed in 90fb27be502b5c15083ebf3e41e772797ab6e656, and it seems we did not consider this.

Your second example is a bit trickier than your first example. In the first example, we have meta information, i.e. we know about the batch axis explicitly, and we also can uniquely identify dynamic axes (via the dim tags, indirectly via dyn seq lens). Once dimensions are static, we don't have any information at all anymore (except the dimension value, i.e. just an integer).

For static dimensions, we could still do some heuristics, e.g. consider them as the same if the int is the same. I think we also do, e.g. in the case of `CombineLayer`. What happens for your example when you use `CombineLayer`? See the logic of `Data.get_common_data`. However, this is somewhat error-prone, e.g. once you change your network such the ints become the same.

For the future, we might also make use of more explicit dim tags for such static dims, to make this more explicit, more robust, and not rely on such heuristics. But this is maybe out-of-the-scope of this issue here.

Can you create a branch and add that as a test case? For the test case, I would use dynamic axis though (like [B,T,X,Y] and [T,B,Y,Z], with T being dynamic). Or maybe two test cases, also the one your posted.

You are right, we can use a similar logic as in `Data.get_common_data` to check whether they are in the same order. And if not, I think we have to use a transpose, because there is no way we can use `matmul` otherwise.

`DotLayer` is actually very similar to `einsum` itself. I think in earlier implementations of `tf.einsum`, they had pretty similar code, which would wrap to `matmul` internally. Now I see that they seem to have an own native TF op for it. But I assume this is less efficient than `matmul`. `matmul` is extremely optimized. I think we should use `matmul` if possible.

I don't really know how `transpose`+`matmul` vs `einsum` compares, though (for the case you raise here in the issue). I think `transpose`+`matmul` might still be faster than `einsum`. This would also be a simple addition in our code. `einsum` would need more code, I think. So I would go with the transpose for now. For the future, we might do a performance comparison at some point, to decide whether we should switch to `einsum` for this case or not. But this is not so important now.

**Comment by Zettelkasten** [comment]
I added two test cases for this in e40e7490f677e27d4fefbff1ff200ef5779d50da, one with dynamic `B` and `T` axes and the static one I already mentioned above.

If I try the same thing with a `CombineLayer` instead of the `DotLayer`, it works fine: In that case, the output has the same shape as the `a` output (as expected).
`DotLayer` should be able to work similarly.

If we don't use `tf.einsum`, I agree that we cannot really avoid `tf.transpose` (and `tf.einsum` probably is not cheaper either).
But maybe we can avoid having multiple calls to `tf.transpose` within the `DotLayer`? But probably that does not really make such a big difference right?

**Comment by albertz** [comment]
> But maybe we can avoid having multiple calls to `tf.transpose` within the `DotLayer`?

Yes. But where do you think we would have multiple calls? It depends how we implement the logic.

> But probably that does not really make such a big difference right?

I'm not exactly sure how it works internally. I.e. whether it will be a copy (then it is expensive), or just a view (then it is so cheap that we can just ignore it)

But it's also a matter of keeping our code simple and clean. It's a tradeoff. But we should not make the code too complicated for exotic cases. E.g. in your example cases, there would in any case just be a single transpose.

Maybe you can just use `Data.copy_compatible_to`. And we could later optimize that function further (in a central place, not in `DotLayer`).

`Data.copy_compatible_to` would use multiple transpose calls in the current implementation, if there are multiple axes to be permuted. I.e. it would use multiple calls to `Data.copy_move_axis`. And that uses our `move_axis`, which calls `tf.transpose`.

We can also do the optimization on a lower level. E.g. inside `move_axis`, or maybe in our custom `transpose` wrapper function, we could check whether the input tensor is also coming from another `Transpose` op, and if so, fuse the ops together. (We do such optimization in some other cases. See usage of `check_base_op_type_and_replace`. Or see `simplify_add`.)

But if `transpose` is not a copy of the tensor, but just a view (internally), then all these optimizations would be overkill and not be needed anyway (and also should not be done, to have the code simple). So before starting working on this, we need to verify this.

**Comment by Zettelkasten** [comment]
I also don't know about how transposes are really handled.
But yes, it's not really all that relevant to this problem: We have transposes all over the place anyway in almost every layer, so it shouldn't be the priority for this issue here.
(Plus I'm the first one noticing this issue, so probably in most cases the remaining axes have the same order anyway.)

Yes, the logic of `Data.copy_compatible_to` is similar, but that always operates on entire `Data` objects and not only a subset of their axes.
We could expand that logic there, maybe add an `list[int] except_axes` argument or sth (and then in the `DotLayer`, set this to all variable + reduce axes).
But the logic in `Data.copy_compatible_to` is quite complicated already, I don't really understand what's going on there.

An in my eyes simpler approach would be to just put the logic for this special case within `DotLayer`.
Or add a function called `get_axes_permutations(from: Data, to: Data, axes: list[int]) -> list[int]` (or a different name) somewhere.
What do you think?

**Comment by albertz** [comment]
Yes, `Data.copy_compatible_to` operates on all axes, but you only need a subset. I don't think we should make this function even more complex. It is also a bit more general in that it adds broadcast dims when/where needed. This is also not what you want/need now for this case. This is another argument for having a separate function.

I would maybe introduce a function `Data.copy_matching_axes(self: Data, target: Data, target_axes: list[int]) -> Data`.

**Comment by Zettelkasten** [comment]
Okay perfect, I will implement such a method. Thanks! :)

**Comment by Zettelkasten** [comment]
A `Data.copy_matching_axes(self: Data, target: Data, target_axes: list[int]) -> Data` actually does not do what we need in this case: Rather than "matching" the axes to be identical, we only want their order to be identical.
Therefore I decided to add this more specific function to `DotLayer` itself.

The commit adb7bfeabe86fff41cd90958e80cbd0ea66f4aea fixes this from what I can tell. All tests pass and my own configs still seem to work.
However, the logic is a bit more specific then I would've hoped. For example there are cases where the time_dim_axis has a size_placeholder, while the other one does not: For example, this is the case in the `test_rec_subnet_eval_init_out_apply0` test in `test_TFEngine.py`. I added a special case for the logic there.
There probably are other cases missing.

Does anybody know a better solution to this?

**Comment by albertz** [comment]
> A `Data.copy_matching_axes(self: Data, target: Data, target_axes: list[int]) -> Data` actually does not do what we need in this case: Rather than "matching" the axes to be identical, we only want their order to be identical.

Why? I thought the issue is about the matching (rem) axes, not the others (red or var axes). And they should match.

> Therefore I decided to add this more specific function to `DotLayer` itself.

I think it also looks fine.

> The commit [adb7bfe](https://github.com/rwth-i6/returnn/commit/adb7bfeabe86fff41cd90958e80cbd0ea66f4aea) fixes this from what I can tell. All tests pass and my own configs still seem to work.
> However, the logic is a bit more specific then I would've hoped. For example there are cases where the time_dim_axis has a size_placeholder, while the other one does not: For example, this is the case in the `test_rec_subnet_eval_init_out_apply0` test in `test_TFEngine.py`. I added a special case for the logic there.
> There probably are other cases missing.
> Does anybody know a better solution to this?

This can happen during template construction.
But shouldn't this be handled by `DimensionTag.is_equal`? Maybe some option need to be set for this (this code is non-straightforward, I always forget the exact meaning of all these options). Or maybe a new option needs to be introduced.

**Comment by Zettelkasten** [comment]
> Why? I thought the issue is about the matching (rem) axes, not the others (red or var axes). And they should match.

Yes yes, the remaining axes should match, but only have to match in the sense that they are permuted in exactly the same order, but not that the axes are exactly at the same positions.

Yes, we could use such a function to have the same effect, but it's more complicated: We then also need to move all remaining axes to the front of the tensor (because otherwise it could be that we cannot align the `rem_axes` of `a` and `b` if one tensor has a smaller ndim).
It just felt more complicated to implement it that way.

> But shouldn't this be handled by `DimensionTag.is_equal`? Maybe some option need to be set for this (this code is non-straightforward, I always forget the exact meaning of all these options). Or maybe a new option needs to be introduced.

Yea we could change it like that, but then we cannot match the axes based on whether they both are marked as `time_dim_axis` or not, because a `DimensionTag` does not have this information (because `DimensionTag.Types.Time == DimensionTag.Types.Spatial`).
So then we would simply just match a spatial (time or sth else) axes that does not have a `size_placeholder` with any other spatial axes (no matter if that one has one)?

**Comment by albertz** [comment]
> It just felt more complicated to implement it that [`copy_matching_axes`] way.

Yea, probably you are right.

> > But shouldn't this be handled by `DimensionTag.is_equal`? Maybe some option need to be set for this ...
> 
> Yea we could change it like that, but then we cannot match the axes based on whether they both are marked as `time_dim_axis` or not, because a `DimensionTag` does not have this information (because `DimensionTag.Types.Time == DimensionTag.Types.Spatial`).

It questionable whether this matching just via `time_dim_axis` (if other information is unknown) is anyway a good idea. Isn't this pure luck that it works for this case?

> So then we would simply just match a spatial (time or sth else) axes that does not have a `size_placeholder` with any other spatial axes (no matter if that one has one)?

This sounds much better. But this logic should be done as a fallback. I.e. first it should try to match with full information, and if that fails, and there is some unknown dynamic spatial axis, then we can use that. But also only if that is unique. E.g. if there are multiple unknown dynamic spatial axes which would match for that case, it should also fail.

We can introduce some helper functions in `Data` for that. E.g. like:

* `Data.find_matching_dims(self, dim_tag: DimensionTag, **equal_opts) -> List[int]`.
  Would just return all matching axes, given these options.
* `Data.find_matching_dim_map(self, other: Data, other_axes: List[int]) -> Dict[int, int]`
  This would use the logic similar as in your code in adb7bfeab in `translate_a_rem_axis_to_b`, to also keep track of "already taken" axes.
  And it would first use the `equal_opts` as in your code and call `find_matching_dims`. And if that returns an empty list, it would add the further option `match_to_unknown_spatial` or so, and again call `find_matching_dims`.
  If `find_matching_dims` returns a non-empty list, it must also check that it contains exactly only one item, in both cases, such that this is always unique.

Just to verify I understand correctly: There is one `Data` with dyn axis but unknown size (`size_placeholder` empty) (probably due to template construction?), and another `Data` which has the information.

Such problems would probably all go away when we rewrite parts of that logic, such that it always knows the size and it is never unknown. I.e. store `DimensionTag` more directly in `Data`. As I mentioned in #391. Then we would not really need any such heuristics, which are anyway complicated, and will definitely fail in certain cases.

**Comment by Zettelkasten** [comment]
> Just to verify I understand correctly: There is one `Data` with dyn axis but unknown size (`size_placeholder` empty) (probably due to template construction?), and another `Data` which has the information.

Yes exactly.

Thanks for all the comments! I implemented the changes that you suggested, and I think #411 should fix this issue now.
