### ISSUE TITLE
Documentation for implementing new RETURNN layers

### ISSUE THREAD

**Issue by nikita68** [rwth-i6/returnn#45]
Hello,
I'm currently in the process of implementing a new RETURNN TF layer. I noticed that quite a lot of features are well documented, though I recommend adding a better description/tutorial for the following aspects (even if some of the info can be gathered by going through the code & comments):
- General confusion avoidance: In some locations the internal placeholder of an object can be easily confused with a tf.placeholder. Adding a small remark where the tf.placeholder is used should be enough.
- General confusion avoidance: Adding a central list of project specific conventions and best practices (e.g. batch or time major, shape of targets etc.)
- In TFNetworkLayer.py:LayerBase: The sources parameter isn't completely described. Especially interesting is in which order the layers are listed.
- In TFNetworkLayer.py:LayerBase: self.output really needs to have an exact description.
- In TFNetworkLayer.py:LayerBase:transform_config_dict: The description is confusing as to when it needs to be used.
- In TFNetworkLayer.py:_ConcatInputLayer: A description of how the input_data parameter exactly is managed would be helpful.
- In TFNetworkLayer.py:Loss: A general quick intro as to how the loss is constucted and interacts with the general system.

I believe these are the main points concerning the implementation of new layers in RETURNN.

**Comment by albertz** [comment]
This is a bit too vague. Can you point to specific source code lines?
Also, this covers multiple issues. It is better to have separate GitHub issues for each individual issue, so that we can close them.
Also, not sure if you are asking here, or you know the answer to some of these, and could just make the change yourself. In that case, don't open a GitHub issue about it. Just add the documentation yourself.

* E.g. point one: I'm not sure what internal placeholder you mean, and/or how it can be confused with `tf.placeholder`.

* Not sure what project specific conventions you mean. The format of a layer output (batch or time major, shape, etc) is totally up to you. The existing layers just have the output the way they have it because it is the most natural, or because it was the easiest way. When you write your own layer, feel free to use whatever you like.

* Not sure exactly what you mean. You can list it in whatever order you like. It depends on the specific layer what it does with it, whether that matters, etc.

* What description? It's the output of the layer. Of type `Data`. That is already described there.

* Probably you don't need to use it.

* Not sure what you mean by managed. It's only a single line of code: `self.input_data = concat_sources_with_opt_dropout(self.sources, dropout=dropout)`. Are you asking what `concat_sources_with_opt_dropout` does?

* It is documented already. It's done via `transform_config_dict`. If you look into that, you see that it calls a small helper function `_make_loss`, which basically just gets the `Loss` class and constructs it.

**Comment by albertz** [comment]
Added some documentation. Closing this now. Please open specific issues about specific individual issues. If something is still unclear, maybe ask me. I don't think it makes much sense to have a generic issue here like "documentation can be improved". It always can be improved.

**Comment by nikita68** [comment]
I was under the assumption that there were more internal conventions used. I will ask/mark any specific questions and update the docs if I see anything that needs to be improved.
Thanks!
