### ISSUE TITLE
Prohibiting deprecated root level parameters

### ISSUE THREAD

**Issue by JackTemaki** [rwth-i6/returnn#512]
This issue is related to #508 with the aim to collect the root parameters that are deprecated or redundant.

Checking this should then be enforced when introducing  `behaviour_version=1`

Please edit the following lists as needed, e.g. when there is a clear consent:

__Parameters that are no longer allowed to be used__  (RETURNN will throw an error) __:__

Agreed on:
 - disallow `num_inputs`
 - disallow `num_outputs` (-> `extern_data`) 

 
 Discussion:
  - All boolean optimizer parameters, such as: `adam`, `nadam`... etc in favour of using `optimizer`
  - `learning_rate` vs `learning_rates`? 
  - `batching` is redundant with `seq_ordering` in the datasets, and is a misleading name
  - Theano parameters? 
 
 
 Here is a full list of all possible parameters:
 https://gist.github.com/JackTemaki/b8c23b8eba61e4951ea22561f30e54a1
 
Many of those only belong to the Theano backend, and can possibly be ignored

**Comment by albertz** [comment]
I don't understand this issue here. We already have #508 as the base. Why don't you add this comment there?

Now for every single individual change (e.g. removing `num_inputs`/`num_outputs`), we should have a separate issue. We should not mix it all together. All these individual things (e.g. `adam` vs `optimizer`, `learning_rate`, etc) all need separate independent discussions.
