### ISSUE TITLE
`DotLayer` defaults should not use integers, change defaults

### ISSUE THREAD

**Issue by albertz** [rwth-i6/returnn#627]
In general, we should not use (even allow) integers to specify axes. Axes can come in any order, and RETURNN can freely reorder them, so using integers is not safe.

So even having this as the default (`red1=-1, red2=-2, var1=-2, var2=-1`) is not a good idea.

This needs a new behavior version (#508).

**Comment by albertz** [comment]
Somewhat related: #573, #569, #586

**Comment by Zettelkasten** [comment]
Note also for e.g. `GatherLayer` we automatically infer the shared axes between the positions and the params automatically using the dim tags. For me, this logic worked very well in the past.
In a same way, we could also infer the `var1`/`var2` axes as be the axes which are not present in both inputs.
This would also work well for when axis change depending on automatic rec layer optimization, and make a `common` argument that could be specified instead of `var1`/`var2` like discussed in #569 redundant.

I'm not 100% sure if this might be unexpected behavior though. E.g., to compute an dyadic product of a `[F]`-shaped tensor (i.e. compute `v * v^T`), the user could previously use `DotLayer` and set `var1=var2=F` as well as `red1=red2=()`, and then it would do exactly that, giving a `[F1,F2]` tensor.
Now with that change, you would first need to create a copy of the input, rename the axis to something different, and then use `DotLayer`.
But the old solution anyway had some issues: It would not be clear what the output dim tags (here `F1` and `F2`) would be. They should would be the same (I'm really not sure what our implementation currently does), but then you could not reference  the axes uniquely. That would be pretty bad.
With the new solution, we are very explicit what the output dim tags are.

**Comment by albertz** [comment]
@Zettelkasten I think you misunderstood what I meant with this issue. I just want to disallow integers to specify axes here. Basically `allow_int=False` in `get_axes_from_description`.

I maybe your comment was not really related specifically to this issue but more general? But are you proposing sth specific here? Like automatically inferring `var1`/`var2` for `DotLayer`? Then better post this in a separate issue because this is really orthogonal here. (Related is also #636, #691.)

**Comment by albertz** [comment]
> I just want to disallow integers to specify axes here. Basically `allow_int=False` in `get_axes_from_description`.

Well, to extend, this is a bit wrong. This is not just the only thing here. Or at least, when we change the defaults anyway, we should think about what defaults we actually want. We also should differ between the `red*` options and the `var*` options.

For `var1`/`var2`:

- No defaults. Require it to be specified by the user.
- Default to `NotSpecified`. And then automatically infer them (#738)
- Sth like `var1="T"`, `var2="static:-1"` or `var2="F"` is somewhat the original default but not using integers. But I don't like this.

For `red1`/`red2`:

First of all, this could be unified into a single `red` (or `reduce`) option (#636).

Then:

- No defaults. Require it to be explicit by the user.
- Some other defaults, maybe similar to the original. But I don't think there is any good default logic, so I would not do this.

As yet another option, when the user specifies `out_shape` (#597, #706), together with unique dim tags (#632), then we can infer all `var1`/`var2`/`red1`/`red2` from that (as suggested in #636).

**Comment by albertz** [comment]
Speaking about defaults, maybe we should also change `add_var2_if_empty` to `False`?
There was some reason to have it, to make it work both inside the loop and outside, but I don't really remember the details anymore, and I'm not sure if this is still needed (related: #569).
