### ISSUE TITLE
Implicit broadcasting for all inputs might be bad

### ISSUE THREAD

**Issue by albertz** [rwth-i6/returnn#691]
Example for `CombineLayer` (also `EvalLayer`) where you have some input [B,D] and [B,T,D]. Via the current logic, it uses `Data.get_common_data`, and that results in [B,T,D], and then `Data.copy_compatible_to` extends [B,D] to [B,1,D] such that it can be broadcasted. I think this is still fine.

But now consider inputs [B,T,D1] and [B,T,D2]. `get_common_data` would return [B,T,D1,D2], so both (all) inputs would broadcast.
Or inputs [B,T1,D] and [B,T2,D], which would result in [B,T1,T2,D].

Consider also the case where we make the distinction based on dim tags, where D1 and D2 could be different dim tags but have the same dimension.

There are surely valid use cases for this. But I question whether this should be implicit, or whether broadcasting for all inputs should only be allowed in an explicit way. Broadcasting for all inputs means that `get_common_data` returns a strict superset of dimensions over all inputs. Otherwise, there would be at least one input which already contains all dimensions. I think for this case, implicit broadcasting is probably always fine.

For broadcasting of all inputs, this could maybe not what the user intended (maybe he/she expected D1 == D2), and only be a consequence of non-matching dim tags. And the error might only be in later layers, or maybe even no error at all, which might be confusing.

Related is also #597, #634, #632, #706

Maybe it could be allowed only if the user specifies `out_dims` (or `out_shape`). Or more specific for this issue, sth like `broadcast_dims`. The most obvious example is `CombineLayer` (and `EvalLayer`) but there are probably other layers as well. This might also be an issue for all `_ConcatInputLayer` derived layers.

In all cases, it probably needs a new behavior version (#508).

**Comment by Zettelkasten** [comment]
I understand that this could be an issue. I personally never really ran into it, but this is also because I look at / think about the output shapes very frequently when I write a config.

Also related is the logic currently in `GatherLayer`, where the shared dims are also inferred as "common" dims between inputs and positions. If the user accidentally got this wrong, the output would also have too many axes. There specifying `out_shape` could also help / maybe should be made mandatory.

About some explicit `broadcast_dims` arg: This is basically how the `var1`/`var2` arguments for `DotLayer` are currently.
And for `GatherLayer`, you could also do the same and introduce some `input_var`/`position_var` or so.
But: I really like how straight-forward and elegant it is to use `GatherLayer` how it is right now, where you basically do not have to specify anything but it also works exactly how it should if all dim tags were set up correctly before.
So here I wouldn't personally want to set something like this. Rather, I'd like RETURNN to check that my assumption of my `out_shape` was correct, which I right now have to do manually.
Similarily, I would also want `DotLayer` to infer the `var1`/`var2` dims automatically (as in #636).

But we can also allow both options. If people don't use `out_shape`, then it might be awkward to have to specify it fully for one layer.

Also there are probably still many open questions with how `out_shape` would work, we should make a separate issue about it. E.g., how to handle dim tags that are different because of rec loop optimization? Or because of `CondLayer`, when the out dims may be totally different?

**Comment by albertz** [comment]
Regarding `out_shape`, I created #706. Let's do all related discussion over there.

**Comment by albertz** [comment]
We should be a bit more specific here. So this is now specifically about `CombineLayer` (including `EvalLayer`). (Maybe there are other layers but then maybe we should make separate issues about them.)

@Zettelkasten so you proposed to add a `broadcast_dims` option? Which contains a list of all dims (dim tags? or what exactly?) which are allowed to be broadcasted?

But what is the default? The empty list? The argument here was that broadcasting like [B,T,D] + [D] or so is fine (so there is one tensor which contains all dims), only [D1] + [D2] = [D1,D2] is not (at least not implicit). An empty list would also disallow the first case though.

Or maybe we disallow implicit broadcasting for all inputs when no `out_shape` is given (#597, #706).

Still allow implicit broadcasting if it only happens for some inputs but not for all. I.e. when there is one input which has all dimensions, then be fine with broadcasting for other inputs.

**Comment by Zettelkasten** [comment]
> @Zettelkasten so you proposed to add a `broadcast_dims` option? Which contains a list of all dims (dim tags? or what exactly?) which are allowed to be broadcasted?

Hm no sorry, I rather said that I think I personally wouldn't want to use such `broadcast_dims` option but instead just specify `out_shape` directly. But I think we agree anyway that we would still allow this kind of broadcasting even if `broadcast_dims` is not specified but `out_shape` is.

> Or maybe we disallow implicit broadcasting for all inputs when no out_shape is given (#597, #706).

Yes. I would prefer this I think. I would rather work on #706, and then see how that feels like and how much it makes sense to use it. If we would then anyway specify `out_shape` for every layer always, or at least for all few important layers (like for the end of each module or so), then I think this would be enough. Then we don't really need to think about this issue specifically. And then it doesn't really matter if we have this extra check here for this implicit broadcasting, as `out_shape` would catch the mistake soon anyway.

> Still allow implicit broadcasting if it only happens for some inputs but not for all. I.e. when there is one input which has all dimensions, then be fine with broadcasting for other inputs.

Yeah. I think there is nothing wrong with that.
