### ISSUE TITLE
Multi GPU training with horovod not working as intended

### ISSUE THREAD

**Issue by deep-speech** [rwth-i6/returnn#73]
I tried using horovod with a single node multi gpu configuration for LM training. 
Enabled following flags in the config.
use_horovod = True
horovod_scale_lr = True

With mpirun, the setup runs on 4 GPUs but training time using 4 GPUs is much higher than a single GPU.
0.308 sec/step for 4 GPUs, 0.085 sec/step for 1 GPU
My dataset is approx 40 GB in size.

Could you please suggest if any further configurations need to be done? Why is training performance degrading with additional GPUs?

**Comment by albertz** [comment]
Can you upload the full stdout (with log_verbosity = 5) somewhere?

Which dataset are you using? The `LmDataset` class?

Maybe also try to set `horovod_reduce_type = 'param'` and `horovod_param_sync_step = 50` (or so). This will not accumulate the gradients but instead let each instance train independently and average the params after N steps.

There might be multiple possible bottlenecks:
* E.g. one is the dataset loading (you would see that in the log output; search e.g. for "computing time").
* The syncing / copying of the params dominate over the training. Our native LSTM is quite fast, so copying the data around might just slow it down.
* Maybe other things...

**Comment by albertz** [comment]
Most important is some log like this at the end of an epoch:

    train epoch 101, finished after 1613 steps, 1:52:53 elapsed (45.1% computing time)

(You should see this N times for N GPUs.)
In this example, the computing time is very low. That is the amount of time spend in the TF `session.run`, i.e. really doing some computation. All the other time is spend elsewhere, and the bottleneck is most likely the dataset. The computing time should be at least >=95% or sth like that for good performance.
Also relevant in this output is the number of steps at the end. Compare that to the number of steps with a single GPU. In theory, should should expect more or less:

    number of steps for N GPUs = number of steps for 1 GPU / N

The number of steps is very linear to the total time. So if you don't have this behavior, this is likely due to how we currently select the batches for each GPU, which currently selects every n-th sequence. This will then lead to more padding and thus more total batches. Decreasing the number of bins in your laplace seq length sorting (the option `seq_ordering = 'laplace:...'` of your dataset) will impact this. Maybe try to play around with that.

We have plans to implement a much more efficient and better dataset loading mechanism for multi-GPU training, which should hopefully solve these issues.

**Comment by albertz** [comment]
This is also urgent for us, but we don't have a concrete timeline.

**Comment by albertz** [comment]
Note that we still do not have the new dataset loading mechanism (this is still on our TODO list).
But we have improved the `HDFDataset` speed, so that it might not be as important anymore (for now). Check some recent RETURNN version, use `HDFDataset`, and make sure that you have `cache_size=0` in your config, and that the HDF file is on some fast file system (local disk or very fast network).

**Comment by deep-speech** [comment]
Thanks for the update.

**Comment by yanghongjiazheng** [comment]
Is there any new dataset loading mechanism for multiGPU training?   The HDFDataset do help improve the training  efficiency. However, the online data augmentation can not be done this way

**Comment by albertz** [comment]
> However, the online data augmentation can not be done this way [with HDFDataset]

Why not? It should work. Or which variant do you mean? I was thinking about SpecAugment, but maybe you mean the settings from `OggZipDataset`/`LibriSpeechCorpus`? In the latter case, you are right.

> Is there any new dataset loading mechanism for multiGPU training?

Have you read the recent [documentation](https://returnn.readthedocs.io/en/latest/advanced/multi_gpu.html)?

Depending on your settings, `OggZipDataset`/`LibriSpeechCorpus` or also any other dataset should be fine.

Esp, there is a new variant, where you set `horovod_dataset_distribution = "random_seed_offset"`.

**Comment by yanghongjiazheng** [comment]
I find that random_permute is a time consuming approach both in  directly Librispeech training and HDFDatasets dumping.    Is it a profitable data augmentation method or just so so in your opinion?

**Comment by albertz** [comment]
> I find that random_permute is a time consuming approach both in directly Librispeech training and HDFDatasets dumping.

Yes, this is because `random_permute` is implemented via NumPy, and some of its operations also in an non-efficient way (e.g. the time stretching uses interpolation, not simply nearest neighbor).

> Is it a profitable data augmentation method or just so so in your opinion?

It helps a bit. And I think with some tuning, it might help even more. Or some variation of it. Other groups also report that this is helpful (e.g. [here](https://arxiv.org/pdf/1910.13296.pdf)). But I think it definitely needs some further work.

On the technical side, I think it will be easier if we just feed raw wave to TF directly (or maybe even Ogg files, and let TF do the Ogg decode), and then do any kind of data augmentation in TF on raw audio, then feature extraction in TF (MFCC etc is all there and simple to use), and then data augmentation on the features (SpecAugment or so).
