### ISSUE TITLE
CachedDataset2 memory issue

### ISSUE THREAD

**Issue by mennetob** [rwth-i6/returnn#9]
Hey

In [CachedDataset2 ](https://github.com/rwth-i6/returnn/blob/cb7714b44a19617113a0e70d1ef77b4245f24884/CachedDataset2.py#L135)

The command  `self.load_seqs(self.expected_load_seq_start, sorted_seq_idx + 1) ` in `get_seq_length(...)` loads the sequences from `self.expected_load_seq_start` to `sorted_seq_idx + 1` to the cache, right?

So lets assume the situation where the dataset has just been created and thus `self.expected_load_seq_start = 0`
and you want to get the length of every single sequence (as you would want e.g. for calling `Dataset.get_seq_order_for_epoch(...)` which I would call during `init_seq_order(...)`), for this I would then use `get_seq_length(...)`.

This would result in iteratively calling `get_seq_lenth(...)` for all sequence indices but with a fixed `self.expected_load_seq_start = 0`, which would result in the cache finally storing all data in `self.added_data`, right?

The problem here is, that by doing this I run out of memory.

Am I using any of those functions not as they were intended to? Please let me know if I am doing anything wrong here.

The obvious fix for me would be to overwrite `get_seq_length(...)` in my dataset, but I just wanted to check if that is maybe a general bug, that is worth fixing in CachedDataset2.

Thanks

 @albertz @doetsch

**Comment by albertz** [comment]
The behavior of `get_seq_length` is correct.

`load_seqs` is supposed to load some seqs and make them available, so that `get_data` etc will work for those seqs. If there is no other call to `load_seqs`, those seqs must be kept available - that is the expected behavior of `load_seqs`.

`get_seq_length` can get called for some future seq which was not yet loaded (but usually only the next one), that is why it internally calls `load_seqs` in that case, but in such a way that it will not remove the other seqs from memory.

`init_seq_order` with the argument "sorted" (or related) will normally use `get_seq_length` but that will not work as you describe. But that should not be the case for `CachedDataset2` - its implementation does not support "sorted" or any other option. Any sorting will not work for the `CachedDataset2` because this dataset is implemented in such a way that it has no real control over the sorting logic. So, usually you are supposed to implement `init_seq_order` yourself if you want to have some control. See the derived versions of `CachedDataset2.init_seq_order` for some examples.

I just looked at the `RawWavDataset` which you might relate to. You either should load in advance the length of each sequence (you can just take the file-length instead, that will preserve the right order) to support the "sorted" or related sorting options. Maybe do that in a lazy way, so the passed function `get_seq_len` to `get_seq_order_for_epoch` can load it at the first call. Or otherwise, just pass `get_seq_len=None` and that will also be fine - in that case, "sorted" or related sorting options will not be supported.

**Comment by mennetob** [comment]
Thanks.

So for the completion of the Issue my solution is the following:

If I understand correctly the "sorted" option is not really supported by CachedDataset2.

But it seems to me that due to the [initialization of dev dataset](https://github.com/rwth-i6/returnn/blob/cb7714b44a19617113a0e70d1ef77b4245f24884/rnn.py#L226), the `seq_ordering` option of the corss validation set in training is set to "sorted" by default?

The config option "batching" only affects the training_set but not the dev_set.
So simply adding the option "seq_ordering": "default" to my specification of the dev_dataset seems to be a sufficient work aroung for my Problem.

**Comment by albertz** [comment]
`CachedDataset2` itself will ignore the seq_ordering option. In all cases, it's up to your implementation to also ignore that (e.g. the `ExternSprintDataset` will just ignore it, like some others do as well), throw an error or do something sensible. Using `get_seq_order_for_epoch` with the default `get_seq_length` will not work, as you described.

**Comment by mennetob** [comment]
Yeah sure.

I'm now also setting `get_seq_len=None` in the call of `get_seq_order_for_epoch(...)` as you suggested. But doing this alone will still make me end up in the [sorted branch](https://github.com/rwth-i6/returnn/blob/cb7714b44a19617113a0e70d1ef77b4245f24884/Dataset.py#L210) of `Dataset.get_seq_order_for_epoch(...)` and thus cause an assertion error. 

By setting `seq_ordering": "default"` in the config of the cross validation set, I only avoid entering that if branch. But you are right I might better handle that in the implementation of my dataset.

Thanks.
