### ISSUE TITLE
Scoring individual sentence pairs fails

### ISSUE THREAD

**Issue by julian90** [rwth-i6/returnn#95]
call for scoring individual sentence pairs fails:
python3 rnn.py crnn.config ++task "eval" ++epoch 80 ++load_epoch 80 ++batch_size "600" ++eval_output_file_per_seq ev.scores

log file is attached
[err.log](https://github.com/rwth-i6/returnn/files/2647996/err.log)

**Comment by albertz** [comment]
Btw, as I said, I did not try`eval_output_file_per_seq` at all. I was expecting that you are fixing this. :p (Also, in this case, the fix was trivial. Did you look at the code?) (And there might be further bugs. As said, I did not try it.) (Only open a new issue if you are not able to fix it yourself, after trying. When you are unsure about how to fix it, make a pull request with a possible fix.)
